[net_bn_sample, info_bn_sample] = convnn_mnist(... 
    'sample', ...
  'expDir', 'data/mnist-bnorm-sample', 'batchNormalization', true);
[net_fc_sample, info_fc_sample] = convnn_mnist(...
    'sample',...
  'expDir', 'data/mnist-baseline-sample', 'batchNormalization', false);

[net_bn_shallow, info_bn_shallow] = convnn_mnist(... 
    'shallow', ...
  'expDir', 'data/mnist-bnorm-shallow', 'batchNormalization', true);

[net_bn_deep, info_bn_deep] = convnn_mnist(... 
    'deep', ...
  'expDir', 'data/mnist-bnorm-deep', 'batchNormalization', true);
